// We use this to avoid typos that are not detected by the compiler and might cost you hours to find.

export const FORM_SUBMIT_DATA_STORE = 'FORM_SUBMIT_DATA_STORE';
export const FORM_TOUCH = 'FORM_TOUCH';
export const FORM_UNTOUCH = 'FORM_UNTOUCH';
export const FORM_USER_INFO = 'FORM_USER_INFO';
// export const FOLLOW_UP_SCREEN_ID_STORE = 'FOLLOW_UP_SCREEN_ID_STORE';
export const INIT_TRANSLATES_LOADED = 'INIT_TRANSLATES_LOADED';
export const INIT_MAGIC_CHECKED = 'INIT_MAGIC_CHECKED';
export const LOOKUP_LIST_ITEMS_STORE = 'LOOKUP_LIST_ITEMS_STORE';
export const LOOKUP_LIST_ITEMS_SELECTED_STORE = 'LOOKUP_LIST_ITEMS_SELECTED_STORE';
export const LOOKUP_INPUT_ID_STORE = 'LOOKUP_INPUT_ID_STORE';
export const MESSAGE_BOX1_OPEN = 'MESSAGE_BOX1_OPEN';
export const MESSAGE_BOX1_CLOSE = 'MESSAGE_BOX1_CLOSE';
export const MESSAGE_BOX2_OPEN = 'MESSAGE_BOX2_OPEN';
export const MESSAGE_BOX2_CLOSE = 'MESSAGE_BOX2_CLOSE';
export const ROUTE_STORE = 'ROUTE_STORE';
export const SEARCHTEXT_OVERALL_STORE = 'SEARCHTEXT_OVERALL_STORE';
export const SORT_ITEM_STORE = 'SORT_ITEM_STORE';
export const TRANS_LANGUAGE_STORE = 'TRANS_LANGUAGE_STORE';
export const TRANS_TRANSLATES_STORE = 'TRANS_TRANSLATES_STORE';
export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
